# Generated by Django 3.1 on 2023-05-16 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needed_time', models.TimeField(auto_now_add=True)),
                ('consistency', models.TimeField(auto_now_add=True)),
                ('preferred_time_list', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
        migrations.AddField(
            model_name='routine',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tag'),
        ),
    ]
