# Generated by Django 3.1 on 2023-05-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230516_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixed_routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Needed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='preferred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='routine',
            name='consistency',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='needed_time',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='preferred_time_list',
        ),
        migrations.AlterField(
            model_name='routine',
            name='tags',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='routine',
            name='fixed_times',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.fixed_routine'),
        ),
        migrations.AddField(
            model_name='routine',
            name='needed_times',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.needed'),
        ),
        migrations.AddField(
            model_name='routine',
            name='preferred_times',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.preferred'),
        ),
    ]
