# Generated by Django 3.1 on 2023-05-17 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230516_0754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='preferred',
            new_name='preferred_routine',
        ),
    ]
